### ISSUE TITLE
无头环境下无法导入opencv库

### ISSUE THREAD

**Issue by ODtian** [Starry-OvO/Tieba-Cloud-Review#38]
**简要描述这个bug**

linux服务器无头环境下无法使用 `opencv-contrib-python` 包

**如何复现**

```
Rocky Linux release 8.4
python3.9.7 
```
安装 `requirement.txt` 并运行本库

**你希望程序作出何种行为**

识别到无头环境自动切换安装 `opencv-contrib-python-headless`

**截图（可选）**

无

**Comment by lumina37** [comment]
headless版本应该不包含二维码模块，那个打包作者做了一些裁剪。我Debian服务器也是无GUI环境，装的是有头版本，有头版本应该是能向下兼容无头版本的

**Comment by ODtian** [comment]
```
Traceback (most recent call last):
  File "/root/Tieba-Manager/water_task.py", line 125, in <module>
    import aiotieba
  File "/root/Tieba-Manager/aiotieba/__init__.py", line 9, in <module>
    from .client import *
  File "/root/Tieba-Manager/aiotieba/client.py", line 18, in <module>
    import cv2 as cv
  File "/usr/local/lib64/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib64/python3.8/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```
是这样报错的，我网上查了下最快的解决方法是装无头版本，也确实解决了，不知道是不是版本不一样？
请忽视py3.8，后来改成3.9了

**Comment by lumina37** [comment]
刚测试了一下发现无头版本的imghash和二维码都没问题，确实能用，那就全都改成无头版本吧
requirements.txt已更新

另外CI挂了是因为我大号被封了，问题不大
