### ISSUE TITLE
云审查教程 报错

### ISSUE THREAD

**Issue by RootSir** [Starry-OvO/Tieba-Cloud-Review#57]
Traceback (most recent call last):
  File "/Users/wgl/py/4.py", line 11, in <module>
    asyncio.run(main())
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/wgl/py/4.py", line 7, in main
    async with tb.Database("在这里填你要审查的贴吧名") as brow:
AttributeError: module 'aiotieba' has no attribute 'Database'

**Comment by lumina37** [comment]
`Database` 改成 `MySQLDB` 就可以了
当时重构的时候忘了改文档....刚刚改过来了
