### ISSUE TITLE
转发贴图像init_wh报错

### ISSUE THREAD

**Issue by single-ptilopsis** [Starry-OvO/Tieba-Cloud-Review#71]
**简要描述这个bug**
```
Traceback (most recent call last):
  File "D:\ProgramProject\Tieba\aiotieba\v2.10.1\test.py", line 18, in <module>
    loop.run_until_complete(run())
  File "D:\ProgramProject\3.9\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\ProgramProject\Tieba\aiotieba\v2.10.1\test.py", line 14, in run
    print(img.show_width)
  File "D:\ProgramProject\Tieba\aiotieba\v2.10.1\aiotieba\client\common\typedef\frags.py", line 193, in show_width
    self._init_wh()
  File "D:\ProgramProject\Tieba\aiotieba\v2.10.1\aiotieba\client\common\typedef\frags.py", line 179, in _init_wh
    self._show_width = int(show_width)
ValueError: invalid literal for int() with base 10: '%!s(*string=0xc1847cc0e0)'
```

**如何复现**

```python
import asyncio

import aiotieba as tb


async def run():
    async with tb.Client() as client:
        threads = await client.get_threads('starry')
        for thread in threads:
            if thread.tid != 7905926315:
                continue

            for img in thread.share_origin.contents.imgs:
                print(img.show_width)


loop = asyncio.get_event_loop()
loop.run_until_complete(run())

```

**你希望程序作出何种行为**

输出show_width (show_height同理)

**Comment by lumina37** [comment]
正在大面积重构，估计明晚的更新会修复这个bug

**Comment by n0099** [comment]
starry神发威了！ https://github.com/Starry-OvO/aiotieba/pull/63#issuecomment-1362425993

**Comment by lumina37** [comment]
`2.10.2a1`已经修复
这是最新的develop分支下的结果
```log
<2023-01-09 11:20:46.136> [WARN] [_init_by_type] Unknown fragment type. type=34 frag={'data': type: 34
text: "afsff#2#"
}
560
560
```
